mode: "dev"
port: 8080

log:
  level: "debug"
  filename: "./log/bluebell.log"
  max_size: 1000
  max_age: 3600
  max_backups: 5

mysql:
  host: 10.128.13.42
  port: 13306
  user: root
  password: qwer123
  db: canyon_dev_v2
  max_open_conns: 100
  max_idle_conns: 20

redis:
  host: 127.0.0.1
  port: 16379
  db: 0